[package]
name = "ap-bot-main"
version = "0.1.0"
edition = "2021"

[dependencies]
ap_rs = { path = "../archipelago_rs", package = "archipelago_rs" }
rand = "0.8.5"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
