name: PR Code Checks

on:
  pull_request:
    branches:
      - master

jobs:
  pr-checks:
    name: PR Code Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Cargo test
        run: cargo test -p ArchipelaPal

        # Do not deny on clippy warnings, for now.
        # Manually review clippy's findings
      - name: Clippy
        run: cargo clippy -p ArchipelaPal -- -W clippy::all

      - name: Format Check
        run: cargo fmt -p ArchipelaPal -- --check
