name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: [windows-2019, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
