name: Release

on:
  push:
    tags:
      - 'v*'

env:
  LINUX_GNU_TARGET: x86_64-unknown-linux-gnu
  WINDOWS_GNU_TARGET: x86_64-pc-windows-gnu

# Should run the following steps:
# Checkout
# `cargo build` to get both a linux and windows binary
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Make APWorld
        run: |
          cd ./world
          ./make_apworld.sh
          cd -

      - name: Setup Targets
        run: |
          rustup target add ${{ env.LINUX_GNU_TARGET }}
          rustup target add ${{ env.WINDOWS_GNU_TARGET }}

          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 gcc

      - name: Build Linux Binary and Zip
        run: |
          cargo build --release --target ${{ env.LINUX_GNU_TARGET }}
          zip -j ap-bot-${{ env.LINUX_GNU_TARGET }}-${{ github.ref_name }}.zip ./target/${{ env.LINUX_GNU_TARGET }}/release/ap-bot

      - name: Build Windows Binary and Zip
        run: |
          cargo build --release --target ${{ env.WINDOWS_GNU_TARGET }}
          zip -j ap-bot-${{ env.WINDOWS_GNU_TARGET }}-${{ github.ref_name }}.zip ./target/${{ env.WINDOWS_GNU_TARGET }}/release/ap-bot.exe

      - name: Debug
        run: ls ./target

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: APBot Release ${{ github.ref }}
          draft: true
          prerelease: true
      
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ap-bot-${{ env.LINUX_GNU_TARGET }}-${{ github.ref_name }}.zip
          asset_name: ap-bot-${{ env.LINUX_GNU_TARGET }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ap-bot-${{ env.WINDOWS_GNU_TARGET }}-${{ github.ref_name }}.zip
          asset_name: ap-bot-${{ env.WINDOWS_GNU_TARGET }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload APWorld
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./world/apbot.apworld
          asset_name: apbot.apworld
          asset_content_type: application/zip
